// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKyg1X5uBTDqTFs9XrvUbWw9GuqFv7fzs',
    appId: '1:488426922109:web:39fd09b5c9300b43dc1114',
    messagingSenderId: '488426922109',
    projectId: 'ig-clone-b0a6e',
    authDomain: 'ig-clone-b0a6e.firebaseapp.com',
    storageBucket: 'ig-clone-b0a6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzF0KaPalfHrnp0spmUyNt3jNky3C_MMM',
    appId: '1:488426922109:android:ae19529a29b73e0edc1114',
    messagingSenderId: '488426922109',
    projectId: 'ig-clone-b0a6e',
    storageBucket: 'ig-clone-b0a6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPpLCQ9XlPSPIjlu7ENK-8kk18Tr0KtU',
    appId: '1:488426922109:ios:9a90aac9829379c3dc1114',
    messagingSenderId: '488426922109',
    projectId: 'ig-clone-b0a6e',
    storageBucket: 'ig-clone-b0a6e.appspot.com',
    iosClientId: '488426922109-8f7oejm8lrcunuhri71phlid2p1lcvt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );
}
